<?xml version="1.0"?>

<robot name="platform" xmlns:xacro="http://www.ros.org/wiki/xacro" >

  <xacro:property name="platform_height" value="0.55" />
  <xacro:property name="platform_radius" value="0.3" />
  <xacro:property name="leg_radius" value="0.02" />
  <xacro:property name="platform_x" value="0.98" />
  <xacro:property name="platform_y" value="0.0" />
  <xacro:property name="platform_z" value="0.0" />

  <xacro:property name="platform_top_thickness" value="0.05"/>

  <xacro:property name="M_PI" value="3.1415926535897931" />

  <!-- P0 -->

  <link name="p0_link">
    <inertial>
      <mass value="100.0" />
      <origin xyz="0.0 0.0 ${platform_height/4}" />
      <inertia ixx="640208333.333333" ixy="0"  ixz="0"
               iyy="640208333.333333" iyz="0"
               izz="20000000" />
    </inertial> 
    <visual>
      <origin xyz="0.0 0.0 ${platform_height/4}" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${leg_radius}" length="${platform_height/2}" />
      </geometry>
      <material name="Black">
		<color rgba="0 0 0 1.0"/>
      </material>
    </visual> 
    <collision>
      <origin xyz="0.0 0.0 ${platform_height/4}" rpy="0.0 0.0 0.0" />
      <geometry>
        <cylinder radius="${leg_radius}" length="${platform_height/2}" />
      </geometry>
    </collision>  
  </link>

  <gazebo reference="p0_link">
    <material>Gazebo/Yellow</material>
    <mu1>1000.0</mu1>
    <mu2>1000.0</mu2>
    <kp>10000000.0</kp>
    <kd>1.0</kd>
    <selfCollide>true</selfCollide>
  </gazebo>

  <!-- P1 -->

  <link name="p1_link">
    <inertial>
      <mass value="100.0" />
      <origin xyz="0.0 0.0 0.0" />
      <inertia ixx="640208333.333333" ixy="0"  ixz="0"
               iyy="640208333.333333" iyz="0"
               izz="20000000" />
    </inertial> 
    <!-- visual>
      <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
      <geometry>
        <cylinder radius="${leg_radius}" length="0.0" />
      </geometry>
      <material name="Black">
		<color rgba="0 0 0 1.0"/>
      </material>
    </visual> 
    <collision>
      <origin xyz="0.0 0.0 0.0" rpy="0.0 0.0 0.0" />
      <geometry>
        <cylinder radius="${leg_radius}" length="0.0" />
      </geometry>
    </collision>-->  
  </link>

  <gazebo reference="p1_link">
    <material>Gazebo/Green</material>
    <mu1>1000.0</mu1>
    <mu2>1000.0</mu2>
    <kp>10000000.0</kp>
    <kd>1.0</kd>
    <selfCollide>true</selfCollide>
  </gazebo>

 <!-- p0_joint -->

  <joint name="p0_joint" type="revolute" >
    <parent link="p0_link" />
    <origin xyz="0.0 0.0 ${platform_z+platform_height/2}" rpy="0 0 0" />
    <child link="p1_link" />
    <limit effort="1000.0" lower="-2.0" upper="2.0" velocity="1.5" />
    <axis xyz="0 1 0"/>
  </joint> 

 <!-- p0_transmission -->

  <transmission name="p0_transmission">
     <type>transmission_interface/SimpleTransmission</type>
           <joint name="p0_joint">
                <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
           </joint>
           <actuator name="p0_motor">
                <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
                <mechanicalReduction>1.0</mechanicalReduction>
           </actuator>
  </transmission>

 <!-- platformtop height is .55+.01+.025=.585 -->
  <link name="platform_top_link">
    <inertial>
      <mass value="1.0" />
      <origin xyz="0.0 0.0 ${platform_top_thickness/2}" />
      <inertia ixx="1" ixy="0"  ixz="0"
               iyy="1" iyz="0"
               izz="1" />
    </inertial> 
    <visual>
      <origin xyz="0.0 0.0 ${platform_top_thickness/2}" />
      <geometry>
        <cylinder radius="${platform_radius}" length="${platform_top_thickness}" />
      </geometry>
      <material name="Grey">
		<color rgba="0.65 0.65 0.65 1.0"/>
      </material>
    </visual> 
    <collision>
      <origin xyz="0.0 0.0 ${platform_top_thickness/2}" />
      <geometry>
        <cylinder radius="${platform_radius}" length="${platform_top_thickness}" />
      </geometry>
    </collision>
  </link>
  <gazebo reference="platform_top_link">
    <material>Gazebo/Red</material>
    <mu1>50.0</mu1>
    <mu2>50.0</mu2>
    <kp>1000000.0</kp>
    <kd>1.0</kd>
    <selfCollide>true</selfCollide>
  </gazebo>

 <!-- p1_joint -->

  <joint name="p1_joint" type="revolute" >
    <parent link="p1_link" />
    <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
    <child link="platform_top_link" />
    <limit effort="1000.0" lower="-2.0" upper="2.0" velocity="1.5" />
    <axis xyz="1 0 0"/>
  </joint>

 <!-- p1_transmission -->

  <transmission name="p1_transmission">
     <type>transmission_interface/SimpleTransmission</type>
           <joint name="p1_joint">
                <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
           </joint>
           <actuator name="p1_motor">
                <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
                <mechanicalReduction>1.0</mechanicalReduction>
           </actuator>
  </transmission>

  <gazebo>
    <!--static>true</static-->
    <canonicalBody>p0_link</canonicalBody>
  </gazebo>


</robot>
