<?xml version="1.0"?>

<robot name="platform" xmlns:xacro="http://www.ros.org/wiki/xacro" >

  <!-- P0 -->
  <link name="platform_origin" />

  <joint name="platform_ground" type="fixed">
      <parent link="platform_origin"/>
      <child link="p0_link" />
      <origin xyz="0 0 ${p0_height/2}" rpy="0 -${M_PI/2} ${M_PI}" />
    </joint>

  <link name="p0_link">
    <inertial>
      <mass value="500.0" />
      <origin xyz="0 0 0" rpy="0 0 0" />
      <inertia ixx="3.2010" ixy="0"  ixz="0"
               iyy="3.2010" iyz="0"
               izz="0.1" />
    </inertial> 
    <visual>
      <origin xyz="0 0 0" rpy="0 ${M_PI/2} 0" />
      <geometry>
        <cylinder radius="${p0_radius}" length="${p0_height}" />
      </geometry>
      <material name="Black">
		<color rgba="0 0 0 1.0"/>
      </material>
    </visual> 
    <collision>
        <origin xyz="0 0 0" rpy="0 ${M_PI/2} 0" />
      <geometry>
        <cylinder radius="${p0_radius}" length="${p0_height}" />
      </geometry>
    </collision>  
  </link>

  <gazebo reference="p0_link">
    <material>Gazebo/Yellow</material>
    <mu1>1000.0</mu1>
    <mu2>1000.0</mu2>
    <kp>10000000.0</kp>
    <kd>1.0</kd>
    <selfCollide>true</selfCollide>
  </gazebo>

  <!-- P1 -->

  <link name="p1_link">
    <inertial>
      <mass value="500.0" />
      <origin xyz="0 0 0" rpy="0 0 0"/>
      <inertia ixx="3.2010" ixy="0"  ixz="0"
               iyy="3.2010" iyz="0"
               izz="0.1" />
    </inertial> 
  </link>

  <gazebo reference="p1_link">
    <material>Gazebo/Green</material>
    <mu1>1000.0</mu1>
    <mu2>1000.0</mu2>
    <kp>10000000.0</kp>
    <kd>1.0</kd>
    <selfCollide>true</selfCollide>
  </gazebo>

 <!-- platform_joint_1 -->

  <joint name="platform_joint_1" type="revolute" >
    <parent link="p0_link" />
    <origin xyz="0 0 0" rpy="${M_PI/2} 0 0" />
    <child link="p1_link" />
    <limit effort="100000.0" lower="-2.0" upper="2.0" velocity="1.5" />
    <axis xyz="0 1 0"/>
  </joint> 

 <!-- p0_transmission -->

  <transmission name="p0_transmission">
     <type>transmission_interface/SimpleTransmission</type>
           <joint name="platform_joint_1">
                <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
           </joint>
           <actuator name="p0_motor">
                <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
                <mechanicalReduction>1.0</mechanicalReduction>
           </actuator>
  </transmission>

  <!-- segment_top -->
  <link name="segment_top">
      <inertial>
          <mass value="500.0" />
          <origin xyz="${platform_height/2+p0_height/2} 0 0" rpy="0 0 0" />
          <inertia ixx="0.1" ixy="0"  ixz="0"
                   iyy="3.2010" iyz="0"
                   izz="3.2010" />
        </inertial> 
        <visual>
            <origin xyz="${platform_height/2+p0_height/2} 0 0" rpy="${M_PI/2} 0 ${M_PI/2}" />
          <geometry>
            <cylinder radius="${leg_radius}" length="${platform_height}" />
          </geometry>
          <material name="Black">
        <color rgba="0 0 0 1.0"/>
          </material>
        </visual> 
        <collision>
            <origin xyz="${platform_height/2+p0_height/2} 0 0" rpy="${M_PI/2} 0 ${M_PI/2}" />
          <geometry>
            <cylinder radius="${leg_radius}" length="${platform_height}" />
          </geometry>
        </collision>  
  </link>

  <gazebo reference="segment_top">
      <material>Gazebo/Green</material>
      <mu1>1000.0</mu1>
      <mu2>1000.0</mu2>
      <kp>10000000.0</kp>
      <kd>1.0</kd>
      <selfCollide>true</selfCollide>
    </gazebo>

   <!-- platform_joint_2 -->

   <joint name="platform_joint_2" type="revolute" >
      <parent link="p1_link" />
      <origin xyz="0.0 0.0 0.0" rpy="0 0 0" />
      <child link="segment_top" />
      <limit effort="100000.0" lower="-2.0" upper="2.0" velocity="1.5" />
      <axis xyz="0 0 1"/>
    </joint>

 <!-- platform top -->
  <link name="platform_top_link">
    <inertial>
      <mass value="5.0" />
      <origin xyz="${platform_top_thickness/2} 0 0" rpy="0 0 0"/>
      <inertia ixx="1.0" ixy="0"  ixz="0"
               iyy="1.0" iyz="0"
               izz="1.0" />
    </inertial> 
    <visual>
        <origin xyz="${platform_top_thickness/2} 0 0" rpy="${M_PI/2} 0 ${M_PI/2}"/>
      <geometry>
        <cylinder radius="${platform_radius}" length="${platform_top_thickness}" />
      </geometry>
      <material name="Grey">
		<color rgba="0.65 0.65 0.65 1.0"/>
      </material>
    </visual> 
    <collision>
        <origin xyz="${platform_top_thickness/2} 0 0" rpy="${M_PI/2} 0 ${M_PI/2}"/>
      <geometry>
        <cylinder radius="${platform_radius}" length="${platform_top_thickness}" />
      </geometry>
    </collision>
  </link>

  <gazebo reference="platform_top_link">
    <material>Gazebo/Red</material>
    <mu1>50.0</mu1>
    <mu2>50.0</mu2>
    <kp>1000000.0</kp>
    <kd>1.0</kd>
    <selfCollide>true</selfCollide>
  </gazebo>

 <!-- top_joint -->

  <joint name="top_joint" type="fixed" >
    <parent link="segment_top" />
    <origin xyz="${platform_height} 0 0" rpy="0 0 0" />
    <child link="platform_top_link" />
  </joint>

 <!-- p1_transmission -->

  <transmission name="p1_transmission">
     <type>transmission_interface/SimpleTransmission</type>
           <joint name="platform_joint_2">
                <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
           </joint>
           <actuator name="p1_motor">
                <hardwareInterface>hardware_interface/PositionJointInterface</hardwareInterface>
                <mechanicalReduction>1.0</mechanicalReduction>
           </actuator>
  </transmission>

  <!-- IMU -->
  <link name="imu_link">
    <inertial>
      <mass value="0.01"/>
      <origin rpy="0.0 0.0 0.0" xyz="0 0 0"/>
      <inertia ixx="0.00000077083" ixy="0" ixz="0" 
               iyy="0.00000077083" iyz="0" 
               izz="0.00000077083"/>
    </inertial>
    <visual>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size="0.03 0.03 0.005"/>
      </geometry>
    </visual>
    <collision>
      <origin rpy="0 0 0" xyz="0 0 0"/>
      <geometry>
        <box size="0.03 0.03 0.005"/>
      </geometry>
    </collision>
  </link>

  <gazebo reference="imu_link">
    <material>Gazebo/Green</material>
  </gazebo>

  <!-- IMU joint -->
  <joint name="imu_joint" type="fixed">
    <axis xyz="1 0 0"/> <!-- 0 1 0 -->
    <origin rpy="${M_PI/2} 0 ${M_PI/2}" 
    xyz="${platform_top_thickness+0.0025} ${platform_radius/2} ${platform_radius/2}"/>
    <parent link="platform_top_link"/>
    <child link="imu_link"/>
  </joint>

  <!-- The imu sensor -->
  <gazebo reference="imu_link">
    <gravity>true</gravity>
    <sensor name="imu_sensor" type="imu">
      <always_on>true</always_on>
      <visualize>true</visualize>
      <plugin filename="libgazebo_ros_imu_sensor.so" name="imu_plugin">
        <topicName>/imu/data</topicName>
        <bodyName>imu_link</bodyName>
        <updateRateHZ>1000.0</updateRateHZ>
        <gaussianNoise>0.0</gaussianNoise>
        <xyzOffset>0 0 0</xyzOffset>
        <rpyOffset>0 0 1.05</rpyOffset>
        <frameName>imu_link</frameName>
      </plugin>
      <pose>0 0 0 0 0 0</pose>
    </sensor>
  </gazebo>

  <gazebo>
    <!--static>true</static-->
    <canonicalBody>p0_link</canonicalBody>
  </gazebo>


</robot>
