joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

platform_computed_torque_controller:
  type: effort_controllers/PlatformComputedTorqueController
  joints:
    - wam_joint_1
    - wam_joint_2
    - wam_joint_3
    - wam_joint_4
    - wam_joint_5
    - wam_joint_6
    - wam_joint_7
  Kp: [25.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 
      0.0, 25.0, 0.0, 0.0, 0.0, 0.0, 0.0, 
      0.0, 0.0, 25.0, 0.0, 0.0, 0.0, 0.0, 
      0.0, 0.0, 0.0, 25.0, 0.0, 0.0, 0.0, 
      0.0, 0.0, 0.0, 0.0, 25.0, 0.0, 0.0, 
      0.0, 0.0, 0.0, 0.0, 0.0, 25.0, 0.0, 
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 25.0]
  Kd: [10.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 
      0.0, 10.0, 0.0, 0.0, 0.0, 0.0, 0.0, 
      0.0, 0.0, 10.0, 0.0, 0.0, 0.0, 0.0, 
      0.0, 0.0, 0.0, 10.0, 0.0, 0.0, 0.0, 
      0.0, 0.0, 0.0, 0.0, 10.0, 0.0, 0.0, 
      0.0, 0.0, 0.0, 0.0, 0.0, 10.0, 0.0, 
      0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 10.0]
  gravity: {x: 0.0, y: 0.0, z: -9.8}
  chain: {root: "wam_origin", tip: "wam_tool_plate"}
  priority: 99
