joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 100

rma_controller:
  type: effort_controllers/RMAController
  joints:
    - wam_joint_1
    - wam_joint_2
    - wam_joint_3
    - wam_joint_4
    - wam_joint_5
    - wam_joint_6
    - wam_joint_7
  Kp: [25.0, 0.0, 0.0, 0.0, 0.0, 0.0, 
      0.0, 25.0, 0.0, 0.0, 0.0, 0.0, 
      0.0, 0.0, 25.0, 0.0, 0.0, 0.0, 
      0.0, 0.0, 0.0, 5.0, 0.0, 0.0, 
      0.0, 0.0, 0.0, 0.0, 5.0, 0.0, 
      0.0, 0.0, 0.0, 0.0, 0.0, 5.0] 
  Kd: [10.0, 0.0, 0.0, 0.0, 0.0, 0.0, 
      0.0, 10.0, 0.0, 0.0, 0.0, 0.0, 
      0.0, 0.0, 10.0, 0.0, 0.0, 0.0, 
      0.0, 0.0, 0.0, 5.0, 0.0, 0.0, 
      0.0, 0.0, 0.0, 0.0, 5.0, 0.0, 
      0.0, 0.0, 0.0, 0.0, 0.0, 5.0]
  Gv: 30.0
  joint_limits:
    wam_joint_1:
      has_position_limits: true
      min_position: -2.6
      max_position: 2.6
    wam_joint_2:
      has_position_limits: true
      min_position: -2
      max_position: 2
    wam_joint_3:
      has_position_limits: true
      min_position: -2.8
      max_position: 2.8
    wam_joint_4:
      has_position_limits: true
      min_position: -0.9
      max_position: 3.1
    wam_joint_5:
      has_position_limits: true
      min_position: -4.76
      max_position: 1.24
    wam_joint_6:
      has_position_limits: true
      min_position: -1.57
      max_position: 1.57
    wam_joint_7:
      has_position_limits: true
      min_position: -3.0
      max_position: 3.0 
  gravity: {x: 0.0, y: 0.0, z: -9.8}
  chain: {root: "wam_origin", tip: "wam_tool_plate"}
  priority: 99
